### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película por id
GET http://localhost:3000/movies/bdba2ab6-6c95-11ee-abb7-b5527e7f059a

### Recuperar todas las películas por un género
GET http://localhost:3000/movies?genre=ACTION

### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película
PATCH http://localhost:3000/movies/8176ed08-72cd-11ee-abb7-b5527e7f059a
Content-Type: application/json

{
  "test": 111,
  "year": 2023
}


### delete
DELETE http://localhost:3000/movies/e7266ac6-72c7-11ee-abb7-b5527e7f059a


### Prod URLS

### Movies

GET https://node-course-dev-xrkn.1.us-1.fl0.io/movies